name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Bingo
      run: |
        cd bingo
        yarn --frozen-lockfile --non-interactive
        yarn build
        yarn test
        cd ..
      env:
        CI: true
    - name: Build Switch
      run: |
        cd switch
        yarn --frozen-lockfile --non-interactive
        yarn build
        yarn test
        cd ..
      env:
        CI: true
