name: Deploy

on:
  push:
    branches:    
      - master 

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build
      run: |
        cd bingo
        yarn --frozen-lockfile --non-interactive
        yarn build
        yarn test
        cd ../switch
        yarn --frozen-lockfile --non-interactive
        yarn build
        yarn test
        cd ..
      env:
        CI: true
    - name: View dir
      run: |
        ls -la
    - name: Deploy Bingo
      uses: contention/rsync-deployments@v1.0.0
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      with:
        args: '"", "-a ./bingo/build/", "circleci@10people.co.uk:~/lab/bingo/"'
    - name: Deploy Switch
      uses: contention/rsync-deployments@v1.0.0
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      with:
        args: '"", "-a ./switch/build/", "circleci@10people.co.uk:~/lab/switch/"'

    
