name: Deploy

on:
  push:
    branches:    
      - master 

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build Bingo
      run: |
        cd bingo
        yarn --frozen-lockfile --non-interactive
        yarn build
        yarn test
        cd ..
      env:
        CI: true
    - name: Build Switch
      run: |
        cd switch
        yarn --frozen-lockfile --non-interactive
        yarn build
        yarn test
        cd ..
      env:
        CI: true
    - name: Set Up Deploy
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        SSH_PATH="$HOME/.ssh"
        mkdir "$SSH_PATH"
        echo "$DEPLOY_KEY" > "$SSH_PATH/id_rsa"
        chmod 400 "$SSH_PATH/id_rsa"
        echo '10people.co.uk,139.59.197.112 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEC+H4axl5nWwKr683pS6R3P4vEvWQUjEWTrAosaPZXAbXOYEMLNB4G/xlmiJ5BIcE4S/IyKlM9wgSRyiBXAQ6k=' >> ~/.ssh/known_hosts
    - name: Rsync bingo
      run: rsync -a --delete bingo/build/ circleci@10people.co.uk:~/lab/bingo
    - name: Rsync switch
      run: rsync -a --delete switch/build/ circleci@10people.co.uk:~/lab/switch
    - name: Deploy lab
      run: ssh circleci@10people.co.uk sudo rsync -a ~circleci/lab/ /root/server/nginx/data/lab
